spring:
  application:
    name: consumer-service
  kafka:
    listener:
      default-retry-template: false
server:
  port: 8082

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0